name: pan
services:
    baidupcs-go:
        stdin_open: true
        tty: true
        container_name: pan
        environment:
            - BDUSS=
            - STOKEN=
        restart: unless-stopped
        image: zhangyiming748/baidupcs-go:latest
        command: entrypoint.sh