name: pan
services:
    baidupcs-go:
        container_name: pan
        environment:
            - BDUSS=${你自己的BDUSS}
            - STOKEN=${你自己的STOKEN}
        restart: unless-stopped
        volumes:
            - ./data:/data
        image: zhangyiming748/baidupcs-go:latest
        command: entrypoint.sh